# Generated by Django 4.2.26 on 2026-03-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReservationLimitSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_per_user_per_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1ユーザーが1日に行える予約の最大件数",
                        verbose_name="1日あたりの予約上限数",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "予約上限設定",
                "verbose_name_plural": "予約上限設定",
            },
        ),
    ]
